### ISSUE TITLE
HTTPError: url= https://tver.jp/api/access_token.php

### ISSUE THREAD

**Issue by johanburati** [kodiful/plugin.video.tver#1]
I am using version 2.0.2 of the plugin with Python 3.8.10, it stopped working recently.
Looks like URL https://tver.jp/api/access_token.php does not exist anymore it returns a *404 Not Found* error.

I am seeing the following error in kodi's log:

```
2022-04-10 09:27:46.971 T:36830    INFO <general>: initializing python engine.
2022-04-10 09:27:47.263 T:36830   ERROR <general>: EXCEPTION: Unknown addon id 'plugin.video.downloader'.
2022-04-10 09:27:48.696 T:36830   ERROR <general>: Skipped 1 duplicate messages..
2022-04-10 09:27:48.696 T:36830   ERROR <general>: plugin.video.tver: common.py(61): urlread: HTTPError: url= https://tver.jp/api/access_token.php
2022-04-10 09:27:48.696 T:36830   ERROR <general>: plugin.video.tver: common.py(62): urlread: HTTPError: code= 404
2022-04-10 09:27:48.696 T:36830   ERROR <general>: plugin.video.tver: common.py(63): urlread: HTTPError: reason= Not Found
2022-04-10 09:27:48.696 T:36830   ERROR <general>: plugin.video.tver: common.py(64): urlread: HTTPError: read= b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\x03}T[k\x13A\x14~\xef\xaf\x18\x07\x91\x14\xb3\xbb)\xf6A\xe8n@\xd3\x14\n\xbd\x88\xb4\xa2O2\xdd=\xc9N\x9d\xbd83\xd96H\xa1\xbb\xfa`[\xa5 \x16)\n\x82\x14Z\xf5\xa1/\xbeH\xb1\x7ffH\xa3\xff\xc2\xd9l\x12\x92j;/{\xae\xdf\xf9\xce\x99\x9dc\xdf\x98]\xae\xad<yPG\xbe\x0cXu\xc2\xce?\x88\x91\xb0\xe9\xe0u\x82\xab\x13\x08\xd9>\x10/\x17\xb4\x18\x80$\xc8\xf5\t\x17 \x1d\xbc\xba2g\xdc\xc5\xa3._\xca\xd8\x80\xe7-\x9a8\xf8\xb1\xb1z\xcf\xa8EAL$]c\x80\x91\x1b\x85\x12B\x9d7_w\xc0k\xc2XfH\x02ppBa#\x8e\xb8\x1c\t\xde\xa0\x9e\xf4\x1d\x0f\x12\xea\x82\xd1S\xca\x88\x86TR\xc2\x0c\xe1\x12\x06\xce\x94Y\x19@I*\x19TW\x1e\x01\xb7\xadB.\xec\x8c\x86\xcf\x10\x07\xe6`!\xdb\x0c\x84\x0f\xa0k\xf8\x1c\x1a\x0e\xb6\x9e\n\x0b8\x8f\xb8\xe9\nQtl\rZ\xb6\xd7"\xaf\xdd\xc7\xf0h\x82\\F\x84\xd0\x9c8\x89c\xe0\xfd\xaa\xe3\xbe\x80\xd0p\xe8\x18w\xc9\x04\xb8\xc1\xa2f\x84\xab6\r\x9aHp\xb7(\xaf\x15k\xe84\xe3\xb0\x89\x11a\xba\xf7\xbc\x11\xd4O\xb04\xd0\xffa\x85$\xb2%\x0c\t\x9b\x12W\xa7+\xd3h)\x92h.j\x85\xde5I\x01\x08A\x9a\x80\x1az\xceF\x80\xab*\xfb\xa2\xb2S\x95\x9d\xa9\xec\xa7J?\xa8\xf4\xf3\xea\xc3\x05\x95\x9evvv\xff\x1c\x1e\xa9\xed\xb4s\xb4s\xf1\xf1\x87J\x0fT\xf6F{U\xba\xa7\x8d\xdd\xfd\xf3\xce\xa7\x93\xce\xeb\xaf\xdd\xf7\'*=V\xe9[\x95~S\xe9\xab\xce\xfe\xe9\xef\x97\xbf.\xb6\xb5E\x07g*\xdbU\xe9\xb9J\x0f\xd5vv\r\xa7\x01\x17[\xc4$D\xd4s\xb0\xab\xbb\x90y\xf3\xb9\xa5\xb0W\xbb\xc7\xef:\xe7\x1a\xf5;\xcaGf\xae\xc7H\xcb\xdd\xe3\xb3\xce\xdeA\x8f\xf8\xb0N\x913Zn\\\x19\xab\x1cI=\xfe\xb8%\xfcK\xa3\xfe7\n_O\xfe\x96\x1b\xc5\xed\x19\xd4\xbb\xba\xf9\xa5\x9ay\x15\x81QQ\xb8\x9c\xc6r\x10\x94\x10\x8ez\x8d#\x07\xdd\x99\xe9\x1b\xbd\xc8m\x05\xfaA\x98\xc4\xf3\xea\x89\x16\x16\xa8\xd0\x0f\x04x\t\xcf./\xd6\x8a\xd7\xb2\x10\x11\x0f<\\F\x8dV\xe8J\x1a\x85\xa5I\xf4b\xc8\xb6@\xbe9\x80\x1e"6A\xd6\x19\xe4\xe2\xfd\xf6\xbcW\xea\x0f}rf$\xb1H2\xf3_\xac_J\x03`\x8cn\x17DGC\xf5f\x98\xd7\x11<!\xact\x05\x8d\xfc\xd0\x06*\x19F\xc1\xc5vPe\xf2r@~X\xe4\x92<\xdf\xe4\x103\xe2B\t[\xe3\xbc\xf2\xb3uI\xbf\x9a\xeb"\x91\xbe\x19\x90\xcdR\xa5\\\xf0\x1e\xc3\xda*\xa3\xa9J\xa52\xb4m\xf5%\xfd#\r\xaf\xc7\xb6\x8a\x85\xa07D\xbe.\xff\x02\xba\x96T\xeb>\x05\x00\x00'
2022-04-10 09:27:48.697 T:36830   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/home/job/.kodi/addons/plugin.video.tver/default.py", line 74, in <module>
                                                       Browse(query).search()
                                                     File "/home/job/.kodi/addons/plugin.video.tver/resources/lib/browse.py", line 140, in search
                                                       jso = json.loads(buf)
                                                     File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--

2022-04-10 09:27:48.742 T:36830    INFO <general>: Python interpreter stopped
2022-04-10 09:27:48.746 T:36829   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.tver/?action=search&query=date%3d2022-04-09%26bc%3d%26genre%3d
2022-04-10 09:27:48.750 T:2545    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.tver/?action=search&query=date%3d2022-04-09%26bc%3d%26genre%3d) failed
2022-04-10 09:27:48.751 T:36832    INFO <general>: initializing python engine.
2022-04-10 09:27:49.014 T:36832   ERROR <general>: EXCEPTION: Unknown addon id 'plugin.video.downloader'.
2022-04-10 09:27:49.018 T:36832    INFO <general>: Skipped 1 duplicate messages..
2022-04-10 09:27:49.018 T:36832    INFO <general>: CPythonInvoker(27, /home/job/.kodi/addons/plugin.video.tver/default.py): script successfully run
2022-04-10 09:27:49.060 T:36832    INFO <general>: Python interpreter stopped
```

**Comment by photodiode** [comment]
For reference take a look at how they set up a user to create the access tokens with the new API here:
https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/tver.py

**Comment by kodiful** [comment]
Sorry for leaving unfixed for long time.
Try new version (3.0) fixed for new API.

**Comment by kodiful** [comment]
close
